#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1594610408                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
# presskit_download_link                    : https://noedgesoftware.com                # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Mortgage Interest Calculator              # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : 0.00                                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Calculate interest to be paid on various mortgage scenarios, comparing different interest rates and points.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Joe Enos
your_link                                 : https://noedgesoftware.com/                     
your_city                                 : Chandler, AZ, USA                                
email_address                             : jtenos@me.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 60seconddev
github_username                           : jtenos
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : View interest amounts
    description                           : Easily calculate amount of interest (including points) paid after 5 years, and in the lifetime of the loan.
    fontawesome_icon_name                 : badge-percent
    
  - title                                 : Compare scenarios
    description                           : View bar graphs comparing up to five scenarios at a time, showing 5-year interest, lifetime interest, and P&I payment.
    fontawesome_icon_name                 : chart-bar



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : white                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown

theme: jekyll-theme-cayman